#!/usr/bin/env bash

set -e

TYPE=$1

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"

GMPDIR=$( cd "$BASEDIR/../../gmp/latest/bin/$TYPE" || cd "$BASEDIR/../../gmp/6.1.2/bin/$TYPE" && pwd -P )
GMPSTATICDIR=$( cd "$BASEDIR/../../gmp/latest/bin/static" || cd "$BASEDIR/../../gmp/6.1.2/bin/static" && pwd -P )

BINDIR=$BASEDIR/bin/$TYPE
SRCDIR=$BASEDIR/src/$TYPE

ROOTBINDIR="$BASEDIR/../../bin/ggnfs"

rm -rf $BINDIR
rm -rf $SRCDIR

mkdir -p $BINDIR
mkdir -p $SRCDIR
mkdir -p $ROOTBINDIR

ROOTBINDIR="$( cd "$ROOTBINDIR" && pwd -P )"

pushd $BASEDIR

if [ ! -f ggnfs-master-3490572.tar.gz ]; then
    git clone https://github.com/radii/ggnfs ggnfs-master-3490572
    git -C ggnfs-master-3490572 checkout 3490572ca8671635a1b8d13a28aef3e34a657fc7
    tar -czf ggnfs-master-3490572.tar.gz ggnfs-master-3490572
    rm -rf ggnfs-master-3490572
fi

popd

pushd $SRCDIR

tar -xz --strip 1 --file=../../ggnfs-master-3490572.tar.gz

ARCH=native

sed -i -e "s|ALLOPT=.*$|ALLOPT=-march=$ARCH -mtune=$ARCH -m64 -pipe|"                           src/Makefile
sed -i -e "s|^INC=\(.*\)$|INC=\1 -I$GMPDIR/include|"                                            src/Makefile
sed -i -e "s|^LIBFLAGS=\(.*\)$|LIBFLAGS=\1 -L$GMPDIR/lib -Wl,-rpath -Wl,$GMPDIR/lib|"           src/Makefile
sed -i -e 's|LSBINS=latsiever polsel|LSBINS=polsel|'                                            src/Makefile
sed -i -e 's|strip $(BINS) ../bin/gnfs-lasieve4I1?e ../bin/pol51*|strip $(BINS) ../bin/pol51*|' src/Makefile

if [ "$TYPE" == "shared" ]; then
    true
elif [ "$TYPE" == "static" ]; then
    sed -i -e "s|^LIBS=\(.*\)$|LIBS=\1 -static -static-libgcc -static-libstdc++|"               src/Makefile
fi

make x86_64
cp bin/* $BINDIR

pushd src/experimental/lasieve4_64

sed -i -e "s|-march=k8 -mtune=k8|-march=$ARCH -mtune=$ARCH|"                             athlon64/Makefile
sed -i -e "s|^CFLAGS=|CFLAGS=-I$GMPSTATICDIR/include |"                                  athlon64/Makefile

sed -i -e "s|-march=k8 -mtune=k8|-march=$ARCH -mtune=$ARCH|"                             Makefile
sed -i -e "s|^INC=|INC=-I$GMPSTATICDIR/include |"                                        Makefile
sed -i -e "s|^LIBFLAGS=|LIBFLAGS=-L$GMPSTATICDIR/lib -Wl,-rpath -Wl,$GMPSTATICDIR/lib |" Makefile

git apply $BASEDIR/asm.patch

cd athlon64
make liblasieve.a
make liblasieveI11.a
make liblasieveI12.a
make liblasieveI13.a
make liblasieveI14.a
make liblasieveI15.a
make liblasieveI16.a
cp *.a ..
cd ..
ln -s athlon64 asm
make
cp gnfs-lasieve4I1{1,2,3,4,5,6}e $BINDIR

popd

popd

if [ "$TYPE" == "static" ]; then
    [ -f $BINDIR/autogplot.sh ]      && ln -srf $BINDIR/autogplot.sh      $ROOTBINDIR/autogplot.sh
    [ -f $BINDIR/def-nm-params.txt ] && ln -srf $BINDIR/def-nm-params.txt $ROOTBINDIR/def-nm-params.txt
    [ -f $BINDIR/def-par.txt ]       && ln -srf $BINDIR/def-par.txt       $ROOTBINDIR/def-par.txt
    [ -f $BINDIR/makefb ]            && ln -srf $BINDIR/makefb            $ROOTBINDIR/makefb
    [ -f $BINDIR/matbuild ]          && ln -srf $BINDIR/matbuild          $ROOTBINDIR/matbuild
    [ -f $BINDIR/matprune ]          && ln -srf $BINDIR/matprune          $ROOTBINDIR/matprune
    [ -f $BINDIR/matsolve ]          && ln -srf $BINDIR/matsolve          $ROOTBINDIR/matsolve
    [ -f $BINDIR/pol51m0b ]          && ln -srf $BINDIR/pol51m0b          $ROOTBINDIR/pol51m0b
    [ -f $BINDIR/pol51m0n ]          && ln -srf $BINDIR/pol51m0n          $ROOTBINDIR/pol51m0n
    [ -f $BINDIR/pol51opt ]          && ln -srf $BINDIR/pol51opt          $ROOTBINDIR/pol51opt
    [ -f $BINDIR/polyselect ]        && ln -srf $BINDIR/polyselect        $ROOTBINDIR/polyselect
    [ -f $BINDIR/procrels ]          && ln -srf $BINDIR/procrels          $ROOTBINDIR/procrels
    [ -f $BINDIR/sieve ]             && ln -srf $BINDIR/sieve             $ROOTBINDIR/sieve
    [ -f $BINDIR/sqrt ]              && ln -srf $BINDIR/sqrt              $ROOTBINDIR/sqrt

    [ -f $BINDIR/gnfs-lasieve4I11e ] && ln -srf $BINDIR/gnfs-lasieve4I11e $ROOTBINDIR/gnfs-lasieve4I11e
    [ -f $BINDIR/gnfs-lasieve4I12e ] && ln -srf $BINDIR/gnfs-lasieve4I12e $ROOTBINDIR/gnfs-lasieve4I12e
    [ -f $BINDIR/gnfs-lasieve4I13e ] && ln -srf $BINDIR/gnfs-lasieve4I13e $ROOTBINDIR/gnfs-lasieve4I13e
    [ -f $BINDIR/gnfs-lasieve4I14e ] && ln -srf $BINDIR/gnfs-lasieve4I14e $ROOTBINDIR/gnfs-lasieve4I14e
    [ -f $BINDIR/gnfs-lasieve4I15e ] && ln -srf $BINDIR/gnfs-lasieve4I15e $ROOTBINDIR/gnfs-lasieve4I15e
    [ -f $BINDIR/gnfs-lasieve4I16e ] && ln -srf $BINDIR/gnfs-lasieve4I16e $ROOTBINDIR/gnfs-lasieve4I16e
fi

exit 0
