#!/usr/bin/env bash

set -e

TYPE=$1

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"

GMPDIR=$( cd "$BASEDIR/../../gmp/latest/bin/$TYPE" || cd "$BASEDIR/../../gmp/6.1.2/bin/$TYPE" && pwd -P )

BINDIR=$BASEDIR/bin/$TYPE
SRCDIR=$BASEDIR/src/$TYPE

ROOTBINDIR="$( cd "$BASEDIR/../../bin" && pwd -P )"

rm -rf $BINDIR
rm -rf $SRCDIR

mkdir -p $BINDIR
mkdir -p $SRCDIR
mkdir -p $ROOTBINDIR

pushd $BASEDIR

if [ ! -f cado-nfs-master-29a7a7cc3.tar.gz ]; then
    git clone https://scm.gforge.inria.fr/anonscm/git/cado-nfs/cado-nfs.git cado-nfs-master-29a7a7cc3
    git -C cado-nfs-master-29a7a7cc3 checkout 29a7a7cc37ede86239e0a34455e657ac780cc78d
    tar -czf cado-nfs-master-29a7a7cc3.tar.gz cado-nfs-master-29a7a7cc3
    rm -rf cado-nfs-master-29a7a7cc3
fi

popd

pushd $SRCDIR

tar -xz --strip 1 --file=../../cado-nfs-master-29a7a7cc3.tar.gz

cp local.sh.example local.sh

echo >> local.sh
echo "GMP=$GMPDIR" >> local.sh
echo "PREFIX=$BINDIR" >> local.sh

make
make install

popd

if [ "$TYPE" == "shared" ]; then
    [ -f $BINDIR/bin/cado-nfs-client.py ] && ln -srf $BINDIR/bin/cado-nfs-client.py $ROOTBINDIR/cado-nfs-client.py
    [ -f $BINDIR/bin/cado-nfs.py ]        && ln -srf $BINDIR/bin/cado-nfs.py        $ROOTBINDIR/cado-nfs.py
fi

exit 0
