#!/usr/bin/env bash

set -e

TYPE=$1
CONFIGUREFLAGS=$2

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"

GMPDIR=$( cd "$BASEDIR/../../gmp/latest/bin/$TYPE" || cd "$BASEDIR/../../gmp/6.1.2/bin/$TYPE" && pwd -P )

BINDIR=$BASEDIR/bin/$TYPE
SRCDIR=$BASEDIR/src/$TYPE

ROOTBINDIR=$BASEDIR/../../bin

rm -rf $BINDIR
rm -rf $SRCDIR

mkdir -p $BINDIR
mkdir -p $SRCDIR
mkdir -p $ROOTBINDIR

pushd $BASEDIR

[ -f ecm-7.0.4.tar.gz ] || wget https://gforge.inria.fr/frs/download.php/file/36224/ecm-7.0.4.tar.gz

popd

pushd $SRCDIR

tar -xz --strip 1 --file=../../ecm-7.0.4.tar.gz

CFLAGS="-m64 -march=native -mtune=native" ./configure --enable-$TYPE $CONFIGUREFLAGS --prefix=$BINDIR --with-gmp=$GMPDIR
make
make ecm-params
make
make check
make install

popd

if [ "$TYPE" == "shared" ]; then
    [ -f $BINDIR/bin/ecm -a ! -f $BINDIR/bin/ecm.exe ] && ln -srf $BINDIR/bin/ecm     $ROOTBINDIR/ecm
    [ -f $BINDIR/bin/ecm.exe ]                         && cp $BINDIR/bin/ecm.exe      $ROOTBINDIR/
    [ -f $BINDIR/bin/libecm-1.dll ]                    && cp $BINDIR/bin/libecm-1.dll $ROOTBINDIR/
fi
