#!/usr/bin/env bash

set -e

TYPE=$1

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"

GMPDIR=$( cd "$BASEDIR/../../gmp/latest/bin/$TYPE" || cd "$BASEDIR/../../gmp/6.1.2/bin/$TYPE" && pwd -P )

BINDIR=$BASEDIR/bin/$TYPE
SRCDIR=$BASEDIR/src/$TYPE

ROOTBINDIR=$BASEDIR/../../bin

rm -rf $BINDIR
rm -rf $SRCDIR

mkdir -p $BINDIR
mkdir -p $SRCDIR
mkdir -p $ROOTBINDIR

pushd $BASEDIR

[ -f cado-nfs-2.3.0.tar.gz ] || wget https://gforge.inria.fr/frs/download.php/file/37058/cado-nfs-2.3.0.tar.gz

popd

pushd $SRCDIR

tar -xz --strip 1 --file=../../cado-nfs-2.3.0.tar.gz

cp local.sh.example local.sh

echo >> local.sh
echo "GMP=$GMPDIR" >> local.sh
echo "PREFIX=$BINDIR" >> local.sh

make
make install

popd

if [ "$TYPE" == "shared" ]; then
    [ -f $BINDIR/bin/cado-nfs-client.py ] && ln -srf $BINDIR/bin/cado-nfs-client.py $ROOTBINDIR/cado-nfs-client.py
    [ -f $BINDIR/bin/cado-nfs.py ]        && ln -srf $BINDIR/bin/cado-nfs.py        $ROOTBINDIR/cado-nfs.py
fi

exit 0
