#!/usr/bin/env bash

set -e

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"

$BASEDIR/gmp/latest/build-shared
$BASEDIR/gmp/latest/build-static

$BASEDIR/gmp-ecm/stable/build-shared
$BASEDIR/gmp-ecm/stable/build-static
$BASEDIR/gmp-ecm/latest/build-shared
$BASEDIR/gmp-ecm/latest/build-static

$BASEDIR/msieve/stable/build-shared
$BASEDIR/msieve/latest/build-shared

$BASEDIR/yafu/stable/build-shared
$BASEDIR/yafu/latest/build-shared

$BASEDIR/ggnfs/latest/build-static

$BASEDIR/cado-nfs/stable/build-shared
$BASEDIR/cado-nfs/latest/build-shared

$BASEDIR/aliqueit/stable/build-shared
$BASEDIR/ecm.py/stable/build
$BASEDIR/factmsieve.py/stable/build

$BASEDIR/ali.pl/latest/build
$BASEDIR/yafu.pl/latest/build

$BASEDIR/gwnum/stable/build-static
$BASEDIR/gwnum/latest/build-static
$BASEDIR/openpfgw/latest/build-static

$BASEDIR/primesieve/latest/build-shared
