#!/usr/bin/env bash

set -e

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"

ROOTBINDIR=$BASEDIR/bin

$BASEDIR/gmp/latest/build-shared
$BASEDIR/gmp-ecm/latest/build-shared
$BASEDIR/msieve/latest/build-shared
$BASEDIR/yafu/latest/build-shared
$BASEDIR/ggnfs/latest/build-shared
$BASEDIR/cado-nfs/latest/build-shared
