#!/usr/bin/env bash

set -e

TYPE=$1
CONFIGUREFLAGS=$2

BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"

BINDIR=$BASEDIR/bin/$TYPE
SRCDIR=$BASEDIR/src/$TYPE

ROOTBINDIR=$BASEDIR/../../bin

rm -rf $BINDIR
rm -rf $SRCDIR

mkdir -p $BINDIR
mkdir -p $SRCDIR
mkdir -p $ROOTBINDIR

pushd $BASEDIR

[ -f gmp-6.1.2.tar.bz2 ] || wget https://gmplib.org/download/gmp/gmp-6.1.2.tar.bz2

popd

pushd $SRCDIR

tar -xj --strip 1 --file=../../gmp-6.1.2.tar.bz2

CFLAGS="-m64 -march=native -mtune=native" ./configure --enable-$TYPE $CONFIGUREFLAGS --prefix=$BINDIR
make
make check
make install

popd

if [ "$TYPE" == "shared" ]; then
    [ -f $BINDIR/bin/libgmp-10.dll ] && cp $BINDIR/bin/libgmp-10.dll $ROOTBINDIR/libgmp-10.dll
fi
